### ISSUE TITLE
Adapting example to use openblas

### ISSUE THREAD

**Issue by cjw85** [pypa/python-manylinux-demo#15]
As a precursor to building a wheel for my own project I wanted to adapt the example to use openblas.

With a few small changes (installing openblas-devel in the container, etc.) I managed to get wheels. However trying to run the code gives segfaults. I resorted to trying to compile and run the small test program below:

    #include <stdio.h>
    #include <cblas.h>
    int main () {
    int i;
    double x[] = { 1, 2, 3 };
    cblas_dscal(3, 4, x, 1);
    for (i = 0; i < 3; ++i)
    printf ("%f\n", x[i]);
    return 0;
    }

However even this segfaults with openblas (fine with atlas). A colleague and I spent quite a while with valgrind and gdb in the manylinux centos container and couldn't find the cause.

Are there minimal examples somewhere of using openblas within a wheel? The numpy etc. builds [here](https://github.com/matthew-brett/manylinux-builds) obviously do it, but I can't decipher the core bits I need to borrow.

**Comment by njsmith** [comment]
I don't know why that would be failing, I'm not sure that anyone watching this repo has worked with openblas either. (I guess I would recommend building your own openblas from source instead of trying to use whatever CentOS 5 ships.) You might have more luck asking on the numpy builds repo or so.

**Comment by cjw85** [comment]
Thanks for the reply. You are correct, I had much better luck by simply compiling my own openblas within the container (with `make DYNAMIC_ARCH=1 USE_OPENMP=0 NUM_THREADS=64 TARGET=NEHALEM` for anyone who ends up here in future). After that everything works much more smoothly.
