### ISSUE TITLE
Skip pure wheels in auditwheel

### ISSUE THREAD

**Issue by letmaik** [pypa/python-manylinux-demo#7]
Currently the demo doesn't have any pure python dependencies. But if you have any, then those go into the wheelhouse/ folder as well. If you then simply loop with `for whl in 'wheelhouse/*.whl'` to call auditwheel [it will fail](https://travis-ci.org/neothemachine/rawpy/jobs/132421339#L1401) for the pure Python packages with "Cannot add platforms to pure wheel". Also, even for binary wheels, I don't want to process any of my dependencies, just my own package, since this is what I would upload to PyPI later, directly from Travis CI. My feeling is that a bit of logic is missing in the demo.

My request: Can the demo be extended to include a small pure Python dependency?

**Comment by njsmith** [comment]
If you only want it to run on your own package, maybe it's as simple as using `for whl in wheelhouse/rawpy-*.whl`?

If that works then maybe you can submit a PR to make the example clearer?

**Comment by letmaik** [comment]
I had the same thought and tried it, and as expected it works. Not sure 
when I could get around to do a PR. I'll see.

**Comment by pombredanne** [comment]
See https://github.com/pypa/auditwheel/issues/47 and see the poor man quick and hacky way here: https://github.com/pombreda/thirdparty-manylinux/blob/3c35a8fa5eee12dec76993a90632e22cc6dbbe01/travis/build-wheels.sh#L24 (not proud of it, I just wanted to get something working quick)

**Comment by marcelm** [comment]
Would it be a solution to add `--no-deps` to the `pip wheel` invocation?

**Comment by lkollar** [comment]
Auditwheel now returns a non-zero exit value on non-platform wheels. #22 updates the build script to skip such wheels.
