### ISSUE TITLE
pip wheel isn't including my extension files

### ISSUE THREAD

**Issue by urschrei** [pypa/python-manylinux-demo#8]
I'm trying to build a wheel using the manylinux container on travis, but while my call to `pip wheel` using the `/opt/python/cp27-cp27mu/bin/pip` builds a wheel, it's excluding .pxd, .pyx, .h, and most importantly, the .so required by my Cython extension, which I'm including in the main package directory, and specifying in my `setup.py` using `extra_link_args=[$ORIGIN]`

When I build the wheel on my local Linux container (ubuntu), using pip 8.1.2, all the files are included, the linker picks up my .so adjacent to the `.pyx` or `.c` source, correctly generates the Cython .so, and the package works as expected. Running `readelf` on my Cython module shows `Library rpath: [$ORIGIN]`.

I'm not sure why this omission is only happening in this Docker image, and I realise that `auditwheel repair` should fix it, but because I'm currently not able to build the .so required by my Cython extension using the manylinux container, I can't use auditwheel. Is there a way I can work around this?

For reference, the Travis manylinux build output is [here](https://travis-ci.org/urschrei/convertbng/jobs/137075945#L689), the Travis OSX build output (which correctly includes the dylib, in this case) is [here](https://travis-ci.org/urschrei/convertbng/jobs/137075946#L761) and my setup.py is [here](https://github.com/urschrei/convertbng/blob/master/setup.py).

**Comment by njsmith** [comment]
Huh, that's pretty mysterious, and I'm not sure what could cause that. There are only a few people looking at this repo though -- if you email the [wheel-builders mailing list](https://mail.python.org/mailman/listinfo/wheel-builders) then there's a better chance that your message will be seen by someone who might know what's happening.

**Comment by njsmith** [comment]
Actually, quick question based on reading your `setup.py`: you have different logic depending on whether cython is installed. I assume that on your local machine you have cython installed. Are you also installing cython in the manylinux docker container?

**Comment by urschrei** [comment]
I hadn't, but I've just added it and it's still missing the files. I'm almost certainly overlooking something, but I can't figure out what. Thanks for the mailing list suggestion, I'll try it now.

## 

steph
